### PR TITLE
Changing the default iframe border to a better-looking one

### LINKED ISSUE #26: Dealing with default border for newbies
I got this message :
Screenshot_2019-07-10 emojicom 🤙 - Collect feedback using emojis

Basically, we have two possibilities :
1. Showing how to remove the border on the site
2. Giving a code without border

Any advice @Andreto @MasterOfTheTiger @KennethSweezy ?

### PR DESCRIPTION
**Pull request by moeenio**
Kinda fixes #26, but doesn't completely remove the border, just does a slightly better-looking one.

@Andreto @MasterOfTheTiger feedback?

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
I do not know.

**Comment by moeenio** [comment]
Ok

**Review by Andreto — COMMENTED** [review]
Better than before and I also think that it's better than no border since this probably fits better on most websites. But maybe we should go the extra mile and style it completely. I think blue border and some border-radius would look nice and have the right scratch feel to it.

**Comment by Andreto** [comment]
Skärmklipp

**Comment by moeenio** [comment]
Maybe border-radius, but I think we'll keep it grey, or else it will "steal" too much attention @Andreto

**Comment by githubfan** [comment]
OK.

**Comment by moeenio** [comment]
@Andreto Please read my previous comment

**Comment by locness3** [comment]
Added border-radius. Merging!

**Comment by moeenio** [comment]
Added some border-radius. What do you think @MasterOfTheTiger @githubfan @Andreto ?

**Comment by Andreto** [comment]
Maybe a lighter color?
And if we going with the grey and not the blue, how it looks now is pretty good.

**Comment by moeenio** [comment]
Made it `lightgrey`, I think I prefer the previous one, but what do you think ?

**Comment by githubfan** [comment]
So do I

**Comment by moeenio** [comment]
Yeah, but let's wait for @Andreto

**Comment by githubfan** [comment]
Ok.

**Comment by githubfan** [comment]
I've been a bit busy with stuff, so I haven't been able to keep up with all
this.

**Comment by moeenio** [comment]
that's fine @githubfan

**Comment by Andreto** [comment]
I prefer the lightgrey, but the darker one gives more contrast and can probably fit on any website. And this feature is for noobs so the esthetics of their site is probably not that important and we should focus on diversity. Go with "grey".

**Comment by moeenio** [comment]
Okay, just made it grey again. Should I merge @Andreto @githubfan ?

**Comment by githubfan** [comment]
Yup

**Review by Andreto — APPROVED** [review]

**Comment by moeenio** [comment]
Ok, merging!

**Pull request merged**
