### PR TITLE
Made improvement to button.

### PR DESCRIPTION
**Pull request by davwat**
I also changed the iframe src to a shorter link, but not the copy code

### CODE REVIEW

**Comment by davwat** [comment]
Done more ui work...

**Comment by moeenio** [comment]
Testing locally

**Comment by moeenio** [comment]
Testing on netlify, problems with local testing.. 🤢

**Review by moeenio — APPROVED** [review]
Won't merge it since I don't really like the css changes. I prefer keeping the `https://locness3.github.io/scratch-profile-embed` so the demo is actually *exactly* the code the user get. Thanks for contributing anyway.

**Comment by moeenio** [comment]
Sorry

**Comment by locness3** [comment]
reopening to test something

**Pull request closed without merging**
