### PR TITLE
Add the new changelog 📝

### PR DESCRIPTION
**Pull request by moeenio**
Add the new Headway-powered changelog.

What do you think @MasterOfTheTiger @Andreto @githubfan (use the deploy preview in the PR checks) ?

### CODE REVIEW

**Comment by moeenio** [comment]
Merging now!

**Comment by Andreto** [comment]
Looks good! Maybe align it better to the rest of the content if possible. (I only have phone available right now, maybe it looks better on on a pc.)

**Comment by moeenio** [comment]
Do you think it's badly aligned ? Or do you think it's inconsistent ?

**Comment by moeenio** [comment]
Maybe using the same color as the "BETA" badge for consistency ? It's actually using the default Headway's styles.

Screenshot_2019-10-18 Embed your Scratch profile on your website - Scratch Profile Embed

**Comment by Andreto** [comment]
Just badly aligned, on my small screen it sits right on the edge. I do like the style of it but you are right that its not that consistent with the rest of the page.

**Comment by Andreto** [comment]
The "veiw changelog" text/activator/button looks good.

**Comment by moeenio** [comment]
I get this on resized desktop browser.

Screenshot_2019-10-18 Embed your Scratch profile on your website - Scratch Profile Embed(1)

Can't use my phone because of #7.
What do you get ?

**Comment by moeenio** [comment]
Also, how is the overall changelog (when you click the "Scratch Profile Embed changelog..." link in the popup) ?

**Comment by Andreto** [comment]
Yes, the text is aligned. It's the box you get when you click on it that's all the way to the side. How does it look on desktop?

**Comment by moeenio** [comment]
Ah, this! Can't use my desktop for now, but it also looks to the side on iPad. I think I might change this on mobile with some css.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by moeenio** [comment]
It isn't a mobile-only issue. Will work on this.
Screenshot_2019-10-19 Embed your Scratch profile on your website - Scratch Profile Embed(1)

**Comment by githubfan** [comment]
> It isn't a mobile-only issue. Will work on this.
> Screenshot_2019-10-19 Embed your Scratch profile on your website - Scratch Profile Embed(1)

Cool, want me to help and create pull request?

**Comment by moeenio** [comment]
No, thanks :)

**Comment by moeenio** [comment]
#42

**Pull request merged**
