### PR TITLE
change input bg and round initial iframe

### LINKED ISSUE #12: Design Suggestions
I think overall the website looks great, but I have some advice to make it more visually pleasing and intuitive.

1. The color of the input and text fields are a bit too similar to the rest of the colors. It does not make the input fields stand out from the rest and they almost look disabled.

2. The styling of the iframe element does not really follow the rest of the page. I don't mean the inside of the iframe, I mean the border and the corners. Maybe round the corners and remove or change the border. I would get that it's styled like that for demonstration purpose but it would do a lot to the site and show the users how it can look.

You can take or leave my advice, but I think its a really good and useful project and I would be happy to help if u need some.

/Andreto

### PR DESCRIPTION
**Pull request by moeenio**
Fixes #12 

View Netlify deployement for preview

### CODE REVIEW

**Comment by moeenio** [comment]
@Andreto

**Comment by Andreto** [comment]
Looks Good

**Comment by moeenio** [comment]
Ok, merging!

**Comment by locness3** [comment]
Heck

**Pull request merged**
