### PR TITLE
Fix changelog popup placement

### PR DESCRIPTION
**Pull request by moeenio**
Make the changelog popup less to the left on desktop, and a bottom drawer on mobile.

Maybe having an overlay on the rest of the content on mobile when the popup is open ?

What do you think @githubfan @Andreto ?
Please approve the PR if you're okay.
You can test with the deploy preview in the checks below.

### CODE REVIEW

**Comment by githubfan** [comment]
I agree with your idea.

**Comment by moeenio** [comment]
Ok, will try to do that now.

**Comment by moeenio** [comment]
Just done that @githubfan !

**Comment by moeenio** [comment]
Hey? @githubfan 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by githubfan** [comment]
Hey

**Comment by locness3** [comment]
Is it good as it is @githubfan ? Use the deploy preview

**Comment by moeenio** [comment]
I made the changelog a "drawer" on mobile. Can you test and give me your approval ? @githubfan

**Comment by moeenio** [comment]
Use the deploy preview here :
Screenshot_2019-10-20 Fix changelog popup placement by locness3 · Pull Request #42 · locness3 scratch-profile-embed

**Comment by githubfan** [comment]
Alright, I'll do soon.

**Review by githubfan — COMMENTED** [review]
Looking good!

**Review by githubfan — APPROVED** [review]
Great!

**Review by githubfan — APPROVED** [review]
Looking good!

**Review by githubfan — APPROVED** [review]

**Review by githubfan — APPROVED** [review]

**Review by githubfan — APPROVED** [review]

**Review by Andreto — APPROVED** [review]
Looks good!
On mobile and desktop.👍

**Comment by moeenio** [comment]
Ok, merging now!

**Pull request merged**
